simulation:
  sim-mode: gpu-headless # gpu-gui cpu-headless
  ml-mode: training # testing
  render-mode: rgb_and_depth_arrays # human rgb_array
  enable-windows: True
  demo: False
  gravity: 9.807
  timestep: 0.008 # 2*(1/240)
  number-of-sub-steps: 4
  number-of-solver-iterations: 50
  contact-erp: 0.2

camera:
  scale-depth-data: False
  width-resolution: 480
  height-resolution: 480
  view-matrix:
    eye-position: [0,0,0.25]
    target-position: [0,0,0.1]
    up-vector: [0,1,0]
  projection-matrix:
    fov: 75
    near-plane: 0.008
    far-plane: 0.16

scene:
  steps-for-objects-to-fall: 50
  drop-bin-enable: False
  bin:
    bin-file: bin0.obj
    scale-factor: [1, 1, 1]
    dimensions: [0.16, 0.16, 0.04]
    position: [0, 0, 0.1]  # in world coordinate framework
    orientation: [90, 0, 0]  # in world coordinate framework
    objects:
      load-random-obj-file: False
      obj-file-to-load: 13x21x5 elektrolit kondenzátor.obj
      scale-factor: [1,1,1]
      min-number-of-objects: 20
      max-number-of-objects: 40
  drop-bin:
    bin-file: bin0.obj
    scale-factor: [1, 1, 1]
    dimensions: [0.16, 0.16, 0.04]
    position: [0, -0.3, 0.1]
    orientation: [90, 0, 0]

workspace:
  lower-bound: [-0.08, -0.08, 0.1]
  upper-bound: [0.08, 0.08, 0.15]

cartesian-robot:
  type: cartesian
  enable-gripper-force-readings: True
  position: [0, 0, 0.37]  # in world coordinate framework  0.37
  orientation: [-1, 0, 0, 0] # in world coordinate framework
  gear:
    erp: 0.1
    maximum-force: 100   # maximum gear force
  gripper:
    tip: [0, 0, 0.136039]  # m, finger tip to gripper base
    gripping-force: 80 # maximum gripping force, N
    maximum-distance: 0.04 # maximum finger moving distance, m
  retract-action:
    maximum-force: 30 # maximum force of retraction action.
    z-distance: 0.37 # retract up distance, m
  place-down:
    position: [0, -0.3, 0.4]
  linear-damping: 0
  angular-damping: 0
  verbose: False
