simulation:
  sim-mode: gpu-gui #gpu-headless cpu-headless
  ml-mode: training #testing
  render-mode: rgb_and_depth_arrays # human rgb_array
  enable-windows: True
  gravity: 9.807
  timestep: 0.005 # 1 / 200
  number-of-sub-steps: 0
  number-of-solver-iterations: 100
  contact-erp: 0.2
  
termination:
  terminate-on-collision-with-bin:
    enable: False
  terminate-after-successful-grabs:
    enable: True
    ensure-grab-is-stable: False
    grabs-before-termination: 1 # ignored

env:
  da: 0.4
  dv: 0.06
  downsample-height: 64
  downsample-width: 64
  success-height: 0.1
  max-steps: 30
  resets-per-setup: 20
  workspace:
    lower-bound: [-0.05, -0.05, 0.02]
    upper-bound: [0.05, 0.05, 1]

camera:
  scale-depth-data: False
  width-resolution: 128
  height-resolution: 128
  view-matrix:
    eye-position: [0.2,0.2,0.45]
    target-position: [0,0,0.3]
    up-vector: [0,0,1]
  projection-matrix:
    fov: 10 # 75
    near-plane: 0.01
    far-plane: 1

robot:
  robot-file: franka_panda/panda.urdf
  clip-delta-actions-to-workspace: True
  enable-gripper-force-readings: False
  position: [-0.6,0,0]
  orientation: [0,0,0] # euler
  poses:
    joint-0: 0
    joint-1: 0.15
    joint-2: 0
    joint-3: -1.65
    joint-4: 0
    joint-5: 1.85
    joint-6: 2.32
    finger-0: 0.02
    finger-1: 0.02

scene:
  steps-for-objects-to-fall: 500
  drop-bin-enable: False
  bin:
    bin-file: bin0.obj
    scale-factor: [1,1,1]
    dimensions: [0.16, 0.16, 0.04]
    position: [0,0,0.01]  # in world coordinate framework
    orientation: [90,0,0]  # in world coordinate framework
    objects:
      load-random-obj-file: True
      obj-file-to-load: sphere
      scale-factor: [2,2,2]
      min-number-of-objects: 1
      max-number-of-objects: 20
  drop-bin:
    bin-file: bin0.obj
    scale-factor: [1, 1, 1]
    position: [0,-0.4,0.1]
    orientation: [90,0,0]
