simulation:
  sim-mode: gpu-gui # gpu-gui cpu-headless
  ml-mode: training # testing # unused but needed for the base env
  render-mode: rgb_array # rgb_array human rgb_and_depth_arrays depth
  enable-windows: True
  gravity: 9.807
  timestep: 0.001 # 1/240
  number-of-sub-steps: 0
  number-of-solver-iterations: 50
  contact-erp: 0.2
  default_view_cam:
    distance: 1.2 #
    yaw: 28.4
    pitch: -39.8
    target: [-0.104, 0.205, 0.34]

termination:
  terminate-on-collision-with-slot:
    enable: True
  terminate-on-collision-with-table:
    enable: True
  terminate-after-successful-placements:
    enable: True
    placements-before-termination: 1
  terminate-on-dropped-peg:
    enabled: True
    dropped-peg-timeout: 100

cameras:
- scale-depth-data: False
  eye-hand-configuration: eye_to_hand  # eye_in_hand
  width-resolution: 480
  height-resolution: 480
  view-matrix:
    eye-position: [0.01,0.01,0.75]
    target-position: [0,0,0.655]
    up-vector: [0,0,1]
  projection-matrix:
    fov: 75
    near-plane: 0.008 # 0.1 also works
    far-plane: 0.5

robot:
  robot-file: franka_panda/panda.urdf
  clip-delta-actions-to-workspace: True
  enable-gripper-force-readings: False
  position: [-0.6,0,0.625]
  orientation: [0,0,0] # degrees euler
  poses:
    joint-0: 0
    joint-1: 0.25
    joint-2: 0
    joint-3: -1.95
    joint-4: 0
    joint-5: 2.05
    joint-6: 2.62
    finger-0: 0.02
    finger-1: 0.02
  impedance:
    inner-steps: 10 # The number of times velocity is updated per call
    delay-steps: 1 # The number of times step_simulation is called per impeded velocity command,
                   #    sets the internal control loop frequency
    sigma: 0.0001 #[0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001] # The diagonal elements of the sigma matrix or a fixed value

scene:
  steps-for-objects-to-fall: 400
  peg-slot:
    geometry: ["square", "cylinder", "triangle", "square_leg"]
    scale-factor: [[1,1,1],[1,1,1],[1,1,1],[1,1,1]]
    slot:
      dimensions: [0.17, 0.17, 0.03]
      position: [0,0,0.625]  # in world coordinate framework
      orientation: [0,0,0]  # in world coordinate framework
    peg:
      geometry: cylinder
      scale-factor: [1,1,1]
      dimensions: [0.02, 0.02, "0.02 or 0.04"]
      spawn-in-hand:
        enabled: True
        axis: 0 # for random do a list of choices. Valid ints in range [0,5]
        angle: 0 # for random put a list of min,max. In deg
        offset: 0 # for random put a list of min,max

  bin:
    bin-file: bin0.obj
    scale-factor: [1, 1, 1]
    dimensions: [0.16, 0.16, 0.04]
    position: [-0.15,0,0.635]
    orientation: [90,0,0]



